---
- name: Install openjdk-8-jdk & Tomcat 7 on RHEL 9
  hosts: tomcat
  gather_facts: true
  vars:
          java_version: java-1.8.0-openjdk-devel.x86_64   # Change to the desired OpenJDK version   
          tomcat_version_dir: 7                         # Change to the desired Tomcat version download directory
          tomcat_version: 7.0.109                         # Change to the desired Tomcat 7 version
          tomcat_install_dir: /opt                        # Change to the desired installation directory
          maven_version: 3.8.8
          maven_install_dir: /opt
          git_repo_dir: /home/ansible/git_projects
  tasks:          
        - name: Create a git_project directory
          file:
            path: "{{git_repo_dir}}"
            state: directory

        - name: Clone Git repository
          git:
            repo: https://github.com/AshviniChavan2904/tomcat-java-project.git
            dest: "{{git_repo_dir}}"
